name: binarysmoothing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - cython
  - tifffile
  - psutil
  - natsort
  # 编译 Cython 代码需要编译器；conda 会自动装 gxx_* / clang_osx-64 对应的 toolchain
